import os
from typing import Callable

import boto3
from botocore.config import Config
from strands import tool

_converse_client = None
_s3_client = boto3.client('s3')
_prompt_cache = {}

DEFAULT_PROMPT = """Extract and verify the complete speech transcript from this video.{timecode_info}

{stt_section}

<instructions>
1. Listen carefully to all speech in the video segment.
2. Compare with the upstream STT results (if provided) and correct any errors.
3. Fill in any missing speech that the STT system failed to capture.
4. Mark genuinely inaudible sections as [inaudible].
5. Preserve speaker changes and natural paragraph breaks.
6. Output the COMPLETE transcript - do not summarize or skip any speech.
7. Do NOT include any correction notes, analysis notes, or meta-commentary about the STT results.

Output format:
- Provide ONLY the transcript text. No corrections list, no notes, no explanations.
- If the target analysis language ({language}) differs from the spoken language, provide a translation after the original.
- If the spoken language is the same as {language}, provide the transcript once only.

Structure your output as:

## Transcript (Original)
[Full transcript in the original spoken language - just the speech text, nothing else]

## Transcript ({language})
[Translation in {language} - ONLY include this section if the spoken language differs from {language}]
</instructions>"""


def _get_converse_client(region: str):
    global _converse_client
    if _converse_client is None:
        _converse_client = boto3.client(
            'bedrock-runtime',
            region_name=region,
            config=Config(read_timeout=600)
        )
    return _converse_client


def _load_prompt_from_s3(prompt_name: str) -> str:
    if prompt_name in _prompt_cache:
        return _prompt_cache[prompt_name]
    bucket = os.environ.get('AGENT_STORAGE_BUCKET_NAME', '')
    if not bucket:
        return ''
    s3_key = f'__prompts/analysis/{prompt_name}.txt'
    try:
        resp = _s3_client.get_object(Bucket=bucket, Key=s3_key)
        content = resp['Body'].read().decode('utf-8')
        _prompt_cache[prompt_name] = content
        return content
    except Exception as e:
        print(f'Failed to load prompt from S3 ({s3_key}): {e}')
        return ''


def create_script_extractor_tool(
    video_uri_getter: Callable[[], str],
    timecode_getter: Callable[[], tuple[str, str]],
    transcribe_segments: list,
    analysis_steps: list,
    region: str = 'us-east-1',
    bucket_owner_account_id: str = '',
    language: str = 'English'
):
    """Create a video script extractor tool using Nova 2 Lite.

    Args:
        video_uri_getter: Function to get video S3 URI
        timecode_getter: Function to get (start, end) timecodes
        transcribe_segments: STT transcription segments from upstream
        analysis_steps: List to append analysis steps
        region: AWS region
        bucket_owner_account_id: AWS account ID that owns the S3 bucket
        language: Target language for analysis output
    """
    model_id = os.environ.get('NOVA_LITE_MODEL_ID', 'global.amazon.nova-2-lite-v1:0')
    max_reasoning_effort = os.environ.get('MAX_REASONING_EFFORT', 'low')

    @tool
    def extract_video_script() -> str:
        """Extract and verify the speech transcript from the video segment.

        This tool analyzes the video using a video-capable model to extract an accurate
        transcript. It cross-references the upstream STT results with the actual
        audio in the video, correcting errors and filling in missing parts.

        Call this tool FIRST before any visual analysis tools.
        No arguments needed - the video segment and STT data are pre-configured.
        """
        video_uri = video_uri_getter()
        if not video_uri:
            return 'No video available for script extraction.'

        start_timecode, end_timecode = timecode_getter()

        # Format STT segments
        stt_text = ''
        if transcribe_segments:
            stt_lines = []
            for seg in transcribe_segments:
                start = seg.get('start_time', '')
                end = seg.get('end_time', '')
                transcript = seg.get('transcript', '')
                stt_lines.append(f'[{start}s - {end}s] {transcript}')
            stt_text = '\n'.join(stt_lines)

        timecode_info = ''
        if start_timecode and end_timecode:
            timecode_info = f'\nAnalyze the segment from timecode {start_timecode} to {end_timecode}.'

        if stt_text:
            stt_section = (
                f'<upstream_stt_results>\n{stt_text}\n</upstream_stt_results>\n\n'
                'The above STT results were generated by an automated speech-to-text system. '
                'Use these as a reference, but verify against the actual audio in the video.'
            )
        else:
            stt_section = (
                'No upstream STT results available. '
                'Extract the speech transcript directly from the video audio.'
            )

        prompt_template = _load_prompt_from_s3('script_extractor_prompt') or DEFAULT_PROMPT
        prompt = prompt_template.format(
            timecode_info=timecode_info,
            stt_section=stt_section,
            language=language
        )

        try:
            s3_location = {'uri': video_uri}
            if bucket_owner_account_id:
                s3_location['bucketOwner'] = bucket_owner_account_id

            video_format = video_uri.rsplit('.', 1)[-1].lower() if '.' in video_uri else 'mp4'

            converse_params = {
                'modelId': model_id,
                'messages': [{
                    'role': 'user',
                    'content': [
                        {
                            'video': {
                                'format': video_format,
                                'source': {
                                    's3Location': s3_location
                                }
                            }
                        },
                        {
                            'text': prompt
                        }
                    ]
                }],
                'additionalModelRequestFields': {
                    'reasoningConfig': {
                        'type': 'enabled',
                        'maxReasoningEffort': max_reasoning_effort
                    }
                }
            }

            print(f'Extracting script from video: {video_uri}')
            print(f'Model: {model_id}, reasoning: {max_reasoning_effort}')
            if start_timecode:
                print(f'Timecode: {start_timecode} - {end_timecode}')
            print(f'STT segments: {len(transcribe_segments)}')

            client = _get_converse_client(region)
            response = client.converse(**converse_params)

            output = response.get('output', {})
            message = output.get('message', {})
            content_blocks = message.get('content', [])

            answer_parts = []
            for block in content_blocks:
                if 'text' in block:
                    answer_parts.append(block['text'])

            answer = '\n'.join(answer_parts)

            analysis_steps.append({
                'step': len(analysis_steps) + 1,
                'tool': 'extract_video_script',
                'question': 'Video Script Extraction',
                'answer': answer
            })

            return answer

        except Exception as e:
            error_msg = f'Error extracting video script: {e}'
            print(error_msg)
            return error_msg

    return extract_video_script
